### ISSUE TITLE
update pagination

### ISSUE THREAD

**Issue by abhishek622** [abhishek622/pokedex-app#2]
You have to change pagination to [MUI Outlined pagination](https://mui.com/components/pagination/#outlined-pagination)
As shown here 👉
![pagination](https://user-images.githubusercontent.com/53276705/161545737-7cbca871-39b5-45ff-ba25-6176faaa68a4.png)

**Comment by Yakup3** [comment]
Can I work on it?

**Comment by abhishek622** [comment]
okay

**Comment by Yakup3** [comment]
My pull request is ready to be reviewed.

**Comment by abhishek622** [comment]
Now you can view your changes on the live website
