### ISSUE TITLE
Update MUI Dialog UI

### ISSUE THREAD

**Issue by abhishek622** [abhishek622/pokedex-app#3]
Update the dialog box UI to make it more user friendly as
👉 ![dialog-box](https://user-images.githubusercontent.com/53276705/161546344-28ba9170-7c9f-4475-bbb2-f13d237c4ff7.png)
or you can also use your imagination to make it look good.

**Comment by Paul0908** [comment]
i would love to fix this issue. It would be really kind if you could assigne it to me.

**Comment by abhishek622** [comment]
okay, go ahead.
The above image is just for the sample if you have a better design in your mind you can implement it.

**Comment by abhishek622** [comment]
Sorry, but I can't assign you to contribute to this repo

**Comment by abhishek622** [comment]
Good Work
