### ISSUE TITLE
Update home page UI

### ISSUE THREAD

**Issue by abhishek622** [abhishek622/pokedex-app#4]
Improve the UI for a better presentation of the Pokemon image, name, and XP.
for example 👉
![home page](https://user-images.githubusercontent.com/53276705/161551223-30073d53-15e4-47dc-88a1-e959c8a576ca.png)

**Comment by Madiena** [comment]
Hi I'd like to contribute to your project by working on this issue if you don't mind (: I'd appreciate a short reply before I start

**Comment by abhishek622** [comment]
okay, go ahead.
The above image is just a sample if you have a better idea you can implement it.
All the best

**Comment by abhishek622** [comment]
Sorry, but I can't assign you to contribute to this repo @Madiena

**Comment by Amanrajlkh** [comment]
Hi I'd like to contribute to your project by working on this issue if you don't mind .

**Comment by abhishek622** [comment]
Great Work 👍🏻
