### ISSUE TITLE
Make all the components of website responsive

### ISSUE THREAD

**Issue by abhishek622** [abhishek622/pokedex-app#5]
This website is not responsive right now you need to update the UI
for example 👉
<img src="https://user-images.githubusercontent.com/53276705/161551655-e23cf6dc-8c3a-4e3b-a0d7-3ce6f8dc9666.png" alt="mobile-view" height="600"/>

**Comment by Lovegupta112** [comment]
Ok.. Could I try

**Comment by Lovegupta112** [comment]
ok so i added some changes , would it be ok 
![podex1](https://user-images.githubusercontent.com/90507983/163589165-6ab6b187-5637-4a56-8caf-9353f764536a.PNG)
![podex2](https://user-images.githubusercontent.com/90507983/163589175-81fe1d40-2e08-4dd4-bec7-4d00483404cd.PNG)

**Comment by abhishek622** [comment]
okay

**Comment by Lovegupta112** [comment]
I have made all the components of website responsive but when i was sending the pull request i saw that whole code has changed . but i will try

**Comment by abhishek622** [comment]
yeah actually the previous contributor changed all the code to class components

**Comment by Lovegupta112** [comment]
Yes , that's why I have to download additional library through npm install  .And it is talking lot of time to download and some errors are also showing .and i don't know more about class component but i wil try

**Comment by abhishek622** [comment]
pull one more time because I have updated the index.js page to react-18 syntax and for this issue, you just need to handle breakpoints of the grid and nothing else

**Comment by Lovegupta112** [comment]
Yes , I know . Actually I used grid system for responsiveness  .

**Comment by Lovegupta112** [comment]
OK I have added  responsiveness in cards element  but one problem is occurring when I am creating new pull request ,it was showing old repo of podexApp for merging in my repository , so should I delete old repo and fork new repo  in which changes are made ?? But then my history will be deleted??
Could you suggest me any option??

**Comment by abhishek622** [comment]
Try to do a git pull. I think this might help

**Comment by abhishek622** [comment]
well done 👍🏻
